ktor {
  deployment {
    port = 8765
    port = ${?MUNCHKIN_PORT}
    sslPort = ${?MUNCHKIN_SSL_PORT}
  }
  application {
    modules = [ com.munchkin.backend.ApplicationKt.module ]
  }
  security {
    ssl {
      keyStore = ${?MUNCHKIN_SSL_KEYSTORE}
      keyAlias = ${?MUNCHKIN_SSL_KEY_ALIAS}
      keyStorePassword = ${?MUNCHKIN_SSL_KEYSTORE_PASSWORD}
      privateKeyPassword = ${?MUNCHKIN_SSL_PRIVATE_KEY_PASSWORD}
    }
  }
}
